spring:
  mail:
    host: smtp.gmail.com
    username: your-email
    password: your-password
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
